Repository executablebooks/github-activity, pull requests merged in 2025-04, with the labels that each got.

#103 ci: run pytest with color and more details
  .github/workflows/tests.yaml
Labels: ci

#105 Install required docs/test dependencies when using nox
  noxfile.py
Labels: maintenance

#106 Fix detail in readthedocs config
  .readthedocs.yml
Labels: maintenance

#107 Add dependabot to bump github actions, and bump them
  .github/workflows/dependabot.yaml
  .github/workflows/publish.yml
  .github/workflows/tests.yaml
Labels: maintenance

#108 Fix ReadTheDocs config - specifying conf location is required
  .readthedocs.yml
Labels: maintenance

#110 ci: test with latest python version as well
  .github/workflows/tests.yaml
Labels: ci

#112 docs: backfill changelog
  CHANGELOG.md
  tests/test_cli/cli_def_branch.md
  tests/test_cli/cli_no_target.md
  tests/test_cli/cli_no_target_pyproject.md
  tests/test_cli/cli_w_parts.md
  tests/test_cli/cli_w_url.md
  tests/test_cli/test_cli_all.md
Labels: documentation

#113 Add changelog for v1.0.0
  CHANGELOG.md
Labels: documentation

#114 Fix publish workflow failure
  .github/workflows/publish.yaml
  .readthedocs.yaml
Labels: maintenance

#115 Add changelog for v1.0.1
  CHANGELOG.md
Labels: documentation

#116 Fix another issue in the publish workflow
  .github/workflows/publish.yaml
Labels: ci

#117 Add changelog for v1.0.2
  CHANGELOG.md
Labels: documentation

#118 ci: fix location of dependabot.yaml
  .github/dependabot.yaml
Labels: ci

#119 ci: fix github action tag in publish workflow
  .github/workflows/publish.yaml
Labels: ci

#120 Add changelog for v1.0.3
  CHANGELOG.md
Labels: documentation

#122 make sure generated anchor links resolve
  docs/index.md
Labels: documentation
